config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:show, :index, :new, :create, :destroy, :patch, :put] do
    resources(:games, except: [:show, :edit, :update, :destroy, :put])
  end

  resources(:games, except: [:put, :edit, :patch, :destroy, :update]) do
    resources :ratings, only: [:new, :create]
  end

  resources :ratings, only: [:new, :create, :index, :update]

  get '/signup', to: "users#new", as: "signup"
  post '/signup', to: "users#create"
  get '/login', to: "sessions#new", as: "login"
  post '/login', to: "sessions#create"
  post '/logout', to: "sessions#destroy"
  get "/auth/facebook", to: "sessions#create_with_fb"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord

    validates :name, presence: true, uniqueness: true
    validate :is_title_case
    before_validation :make_title_case
    has_many :ratings
    has_many :users, through: :ratings


    def ratings_attributes=(attrs)
        attrs.values.each do |hash|
            if hash[:id]
                r = Rating.find_by(id: hash[:id])
                r.update(hash)
            else
                self.ratings.build(hash)
            end
        end
    end



    def is_title_case
        if self.name != self.name.titlecase
            self.errors.add(:name, "must be titlecase")
        end
    end

    def make_title_case
        self.name = self.name.titlecase
    end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

    before_action(:show_helper, except: [:index, :new, :create])
    before_action(:require_login)
    before_action(:index_helper, only: :index)

    layout "application"

    def index
        if params[:user_id]
            user = User.find_by(id: params[:user_id])
            @games = user.games
        end
    end

    def show
    end

    def new
        @game = Game.new
        @game.ratings.build(user: current_user)
        @game.ratings.build(user: current_user)
        @ratings = @game.ratings.select{|r| r.user_id == current_user.id}
    end

    def create
        @game = Game.new(game_params)
        @game.ratings.each {|r| r.user = current_user}
        if @game.save
            flash[:message] = "Successfully created"
            redirect_to game_path(@game)
        else
            @ratings = @game.ratings.select{|r| r.user_id == current_user.id}
            render :new
        end
    end


    def destroy
        @game.delete
        flash[:message] = "Successfully deleted"
        redirect_to games_path
    end


    private

        def game_params
            params.require(:game).permit(:name, ratings_attributes: [:score, :user_id, :id])
        end

        def set_game
            @game = Game.find_by(id: params[:id])
        end


end

app/views/games/_form.erb
<%=form_with(model: @game, builder: CustomFormBuilder) do |f|%>
    <%=f.label("Game Name:") %>
    <%=f.text_field(:name) %>
    <%=f.label("Ratings:") %>
    <%=f.my_fields_for(:ratings, @ratings) do |r| %>
      <%=r.label "Score"%>
      <%=r.number_field :score%>
    <%end%>
    <%=f.submit "Submit"%>
<%end%>

app/views/games/edit.erb
<%=render(partial: "application/errors", locals: {errors: @game.errors.full_messages})%>

<%=render('form')%>

app/views/games/index.html.erb
<h1>All Games</h1>
<%@games.each do |game|%>
  <li><%=link_to(game.name, game_path(game))%></li>
<%end%>

app/views/games/new.erb
<%=render(partial: "application/errors", locals: {errors: @game.errors.full_messages})%>


<%=render('form')%>

app/views/games/show.html.erb
<h1><%=@game.name%></h1>


<%=render partial: 'ratings/ratings', locals: {ratings: @game.ratings, index: false}%><br>


<%=link_to "Add Game to List", new_game_rating_path(@game) %><br><br>