config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:show, :index, :new, :create, :destroy, :patch, :put] do
    resources(:games, except: [:show, :edit, :update, :destroy, :put])
  end

  resources(:games, except: [:put, :edit, :patch, :destroy, :update]) do
    resources :ratings, only: [:new, :create]
  end

  resources :ratings, only: [:new, :create, :index, :update]

  get '/signup', to: "users#new", as: "signup"
  post '/signup', to: "users#create"
  get '/login', to: "sessions#new", as: "login"
  post '/login', to: "sessions#create"
  post '/logout', to: "sessions#destroy"
  get "/auth/facebook", to: "sessions#create_with_fb"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProjectFinal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%if current_user %>
  <%=link_to "All Games", games_path %>
  <%=link_to "New Game", new_game_path %>
  <%=link_to "New Rating", new_rating_path %>
  <%=link_to "All Ratings", ratings_path %>
  <%=link_to "My Games", user_games_path(current_user) %>
  <%= button_to "Log Out", logout_path, method: :post %>

  <%else%>
    <%= link_to "Log In", login_path %>
    <%= link_to "Sign Up", signup_path %>
  <%end%>
  <%=flash[:message]%>
    <%= yield %>
  </body>
</html>

app/views/layouts/games.erb
<h1>We are in the games layout</h1>

<%=yield%>

app/views/layouts/ratings.erb
<h1>We are in the ratings layout</h1>

<%=link_to "All Games", games_path %>
<%=link_to "New Game", new_game_path %>
<%=link_to "New Rating", new_rating_path %>
<%=link_to "All Ratings", ratings_path %>
<%=yield%>